# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.0

executors:
  aws-executor:
    docker:
      - image: circleci/python:3.7.1
  project-executor:
    docker:
      - image: spoonflower/ubuntu-xenial-node-8:0.0.2
  test-executors:
    docker:
      - image: spoonflower/ubuntu-xenial-node-8:0.0.2
      - image: postgres:latest
      - image: redis:latest

aliases:
  - &save
    save_cache:
      name: Save Temporary Workspace
      key: v-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ .Environment.CIRCLE_SHA1 }}
      paths:
        - ~/code
  - &load
    restore_cache:
      keys:
        - v-{{ .Environment.CIRCLE_WORKFLOW_ID }}-{{ .Environment.CIRCLE_SHA1 }}
  - &step_npmauth
    run:
      name: Authenticate to GitHub Package Manager
      command: |
         echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
  - &step_restorecache
    restore_cache:
      keys:
        - npmmodules-{{ checksum "package.json" }}
  - &step_savecache
    save_cache:
      name: Save node_modules cache
      key: npmmodules-{{ checksum "package.json" }}
      paths:
        - node_modules

job_defaults: &defaults
  working_directory: ~/code
  executor: project-executor

jobs:
  build:
    <<: *defaults
    description: Build and Test a Spoonflower NodeJS project
    steps:
      - checkout
      - *step_restorecache
      - *step_npmauth
      - run: npm install
      - *step_savecache
      - run:
          name: Security Audit
          command: npm audit || true
      - run:
          name: Lint
          command: |
             if [ -f ./tslint.json ]; then
                 npm run lint
             fi
      - run:
          name: Make build
          command: | 
             if [ -f ./.circleci/ci.sh ]; then
                echo "Running ./.circleci/ci.sh"
                ./.circleci/ci.sh 
             else
                echo "./.circleci/ci.sh was not found. Running npm run build"
                npm run build
             fi
      - run:
          name: Run tests
          command: npm test
      - run: 
          name: Create build tarball
          command: npm run archive
      - store_artifacts:
          path: ~/code/build.tar.gz
      - *save
  package_s3:
    description: Deploys a build tarfile to a deployment artifact bucket
    executor: aws-executor
    parameters:
      bucket:
        description: "S3 bucket to deploy to"
        type: string
        default: "$ARTIFACT_BUCKET"
      tarfile:
        description: "Name of build tarfile (should end in .tar.gz)"
        type: string
        default: "build.tar.gz"
      working-dir:
        description: "Working directory"
        type: string
        default: "~/code"
    working_directory: << parameters.working-dir >>
    steps:
      - *load
      - aws-s3/copy:
          from: '<< parameters.working-dir >>/workspace/<< parameters.tarfile >>'
          to: 's3://<< parameters.bucket >>/builds/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/$CIRCLE_BUILD_NUM.tar.gz'
      - run: echo "$CIRCLE_BUILD_NUM.tar.gz" > << parameters.working-dir >>/workspace/latest.txt
      - run: aws s3api put-object-tagging --bucket << parameters.bucket >> --key builds/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/$CIRCLE_BUILD_NUM.tar.gz --tagging "TagSet=[{Key=checksum,Value=$CIRCLE_SHA1}]"
      - aws-s3/copy:
          from: '<< parameters.working-dir >>/workspace/latest.txt'
          to: 's3://<< parameters.bucket >>/builds/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BRANCH/latest.txt'
  package:
    <<: *defaults
    description: Publish an NPM package to GitHub
    steps:
      - *load
      - *step_npmauth
      - run:
          name: Version Bump
          command: | 
            CURRENT_YEAR=$(date +%Y)
            CURRENT_MONTH=$(date +%m)
            sed -i "/version/c\  \"version\": \"${CURRENT_YEAR}.${CURRENT_MONTH}.${CIRCLE_BUILD_NUM}\"," package.json
      - run:
          name: Publish package
          command: npm publish --access restricted
