# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

aliases:
  - &step_attachws
    attach_workspace:
      at: /home/circleci
  - &step_npmauth
    run:
      name: Authenticate to GitHub Package Manager
      command: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
  - &step_restorecache
    restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

executors:
  project-executor:
    docker:
      - image: spoonflower/ubuntu-xenial-node-8:0.0.2
jobs:
  build:
    description: Build and Test a Spoonflower NodeJS project
    executor: project-executor
    working_directory: ~/repo/code
    steps:
      - checkout
      - *step_attachws
      - *step_restorecache
      - *step_npmauth
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Security Audit
          command: npm audit || true
      - run:
          name: Lint
          command: |
             if [ -f ./tslint.json ]; then
                 npm run lint
             fi
      - run:
          name: Make build
          command: | 
             if [ -f ./.circleci/ci.sh ]; then
                echo "Running ./.circleci/ci.sh"
                ./.circleci/ci.sh 
             else
                echo "./.circleci/ci.sh was not found. Running npm run build"
                npm run build
             fi
      - run:
          name: Run tests
          command: npm test
      - run: 
          name: Create build tarball
          command: npm run archive
      - store_artifacts:
          path: ~/repo/build.tar.gz
      - persist_to_workspace:
          root: ~/repo
          paths:
            - code
  package:
    description: Publish an NPM package to GitHub
    executor: project-executor
    working_directory: ~/repo/workspace/code
    steps:
      - *step_attachws
      - *step_npmauth
      - run:
          name: Version Bump
          command: | 
            CURRENT_YEAR=$(date +%Y)
            CURRENT_MONTH=$(date +%m)
            sed -i "/version/c\  \"version\": \"${CURRENT_YEAR}.${CURRENT_MONTH}.${CIRCLE_BUILD_NUM}\"," package.json
      - run:
          name: Publish package
          command: npm publish --access restricted
